<template>
  <div class="mod-home">
    <p>一个基于spring boot、spring security、mybatis plus、redis的轻量级、前后端分离、认证授权权限基础框架，开箱即用</p>
    <h2>当前已具备的功能</h2>
    <ol>
      <li>用户登录+滑块验证码</li>
      <li>菜单管理</li>
      <li>角色管理</li>
      <li>用户管理</li>
      <li>权限管理，包括菜单和按钮权限</li>
      <li>操作日志</li>
      <li>在线接口文档</li>
    </ol>
    <h2>技术选型</h2>
    <figure>
      <table
        border="1"
        cellspacing="0"
        cellpadding="5px"
      >
        <thead>
          <tr>
            <th>技术</th>
            <th>版本</th>
            <th>说明</th>
          </tr>
        </thead>
        <tbody>
        <tr>
          <td>JDK</td>
          <td>1.8</td>
          <td>开发环境</td>
        </tr>
          <tr>
            <td>Spring Boot</td>
            <td>2.6.7</td>
            <td>MVC核心框架</td>
          </tr>
          <tr>
            <td>MyBatis</td>
            <td>3.5.0</td>
            <td>ORM框架</td>
          </tr>
          <tr>
            <td>MyBatisPlus</td>
            <td>3.5.5</td>
            <td>基于mybatis，使用lambda表达式的</td>
          </tr>
          <tr>
            <td>knife4j</td>
            <td>3.0.3</td>
            <td>在线接口文档</td>
          </tr>
          <tr>
            <td>redisson</td>
            <td>3.19.3</td>
            <td>对redis进行封装、集成分布式锁等</td>
          </tr>
          <tr>
            <td>hikari</td>
            <td>3.2.0</td>
            <td>数据库连接池</td>
          </tr>
          <tr>
            <td>logback</td>
            <td>1.2.11</td>
            <td>log日志工具</td>
          </tr>
          <tr>
            <td>lombok</td>
            <td>1.18.24</td>
            <td>简化对象封装工具</td>
          </tr>
          <tr>
            <td>hutool</td>
            <td>5.8.15</td>
            <td>更适合国人的java工具集</td>
          </tr>
          <tr>
            <td>fastjson</td>
            <td>1.2.83</td>
            <td>json序列化与反序列化</td>
          </tr>
        <tr>
          <td>jwt</td>
          <td>0.9.1</td>
          <td>token管理</td>
        </tr>
        <tr>
          <td>captcha</td>
          <td>1.3.0</td>
          <td>滑块验证码</td>
        </tr>
        </tbody>
      </table>
    </figure>
    <p>&nbsp;</p>
    <h2>部署教程</h2>
    <h3>1.项目结构</h3>
    <figure>
      <table
        border="1"
        cellspacing="0"
        cellpadding="5px"
      >
        <thead>
        <tr>
          <th>项目</th>
          <th>说明</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>doc</td>
          <td>数据库脚本</td>
        </tr>
        <tr>
          <td>front</td>
          <td>后台管理系统前端代码</td>
        </tr>
        <tr>
          <td>sandy-admin</td>
          <td>后台管理系统后端代码</td>
        </tr>
        <tr>
          <td>sandy-common</td>
          <td>工具包</td>
        </tr>
        <tr>
          <td>sandy-security</td>
          <td>基于spring security的认证和授权代码</td>
        </tr>
        </tbody>
      </table>
    </figure>
    <h3>2.开发环境</h3>
    <figure>
      <table
        border="1"
        cellspacing="0"
        cellpadding="5px"
      >
        <thead>
          <tr>
            <th>工具</th>
            <th>版本</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>jdk</td>
            <td>1.8</td>
          </tr>
          <tr>
            <td>mysql</td>
            <td>5.7+</td>
          </tr>
          <tr>
            <td>redis</td>
            <td>3.2+</td>
          </tr>
        </tbody>
      </table>
    </figure>
    <h3>3.启动</h3>
    <ul>
      <li>推荐使用idea，安装lombok插件，使用idea导入maven项目</li>
      <li>
        将doc/framework.sql导入到mysql中
      </li>
      <li>修改
        <code>application-dev.yml</code> datasource.url、user、password
      </li>
      <li>修改
        <code>application-dev.yml</code> redis.host、redis.port
    </li>
      <li>
        通过
        <code>sandy-admin项目WebApplication</code>启动项目后台接口
      </li>
      <li>
        超级管理员账号：admin/123456
      </li>
    </ul>
    <p>&nbsp;</p>
  </div>
</template>

<style lang="scss" scoped>
.mod-home {
  line-height: 1.5;
}
</style>
